### ISSUE TITLE
BUG: 在群聊中却显示不在群

### ISSUE THREAD

**Issue by KomoriDev** [A-kirami/matcha#123]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

v0.2.5

### 问题描述

申请入群后在群聊中发送指令，可以发送和接受，但matcha会弹窗显示我不是本群成员，同时控制台报错：
（比如我发送 /图像超分）
```shell
08-05 19:07:37 [SUCCESS] nonebot | OneBot V11 2871703871 | [message.group.normal]: Message 10008 from 2740324073@[群:413820772] '/图
像超分'
08-05 19:07:37 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='message', module=sora.plugins.real_esrgan)
08-05 19:07:37 [ERROR] nonebot | Running AlconnaMatcher(type='message', module=sora.plugins.real_esrgan) failed.
(省略部分日志)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1000, data={'message': 'Error: 不是本群成员'}, echo='1')
```
退群后正常接收退群事件：
```shell
08-05 19:09:10 [SUCCESS] nonebot | OneBot V11 2871703871 | [notice.group_decrease.leave]: {'time': 1691233751, 'self_id': 2871703871, 'post_type': 'notice', 'notice_type': 'group_decrease', 'sub_type': 'leave', 'user_id': 2740324073, 'group_id': 413820772, 'operator_id': 2740324073}
```
好像只有我发送 `/图像超分` 指令会遇到上述问题，别的指令不会，但也没响应

### 复现步骤

1. 申请入群
2. 发送指令

### 预期行为

正常响应

### 日志信息
控制台日志（第一个error是我重新打开matcha复现的时候忘记申请入群了）：
<img width="944" alt="6b10ae874abaa56eff7918bfdc40442b" src="https://github.com/A-kirami/matcha/assets/110453675/652c6867-ec37-4397-b654-9d562288fef8">

nb日志：
```shell
08-05 19:06:21 [SUCCESS] nonebot | OneBot V11 2871703871 | [notice.group_increase.approve]: {'time': 1691233581, 'self_id': 2871703871, 'post_type': 'notice', 'notice_type': 'group_increase', 'sub_type': 'approve', 'user_id': 2740324073, 'group_id': 413820772, 'operator_id': 2740324073}
08-05 19:07:37 [SUCCESS] nonebot | OneBot V11 2871703871 | [message.group.normal]: Message 10008 from 2740324073@[群:413820772] '/图
像超分'
08-05 19:07:37 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='message', module=sora.plugins.real_esrgan)
08-05 19:07:37 [ERROR] nonebot | Running AlconnaMatcher(type='message', module=sora.plugins.real_esrgan) failed.
Traceback (most recent call last):
  File "D:\sorabot\sorabot\bot.py", line 25, in <module>
    nonebot.run()
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\mute2\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\sorabot\sorabot\matcher_patch.py", line 46, in simple_run
    await handler(
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 104, in __call__
    values = await self.solve(**kwargs)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\dependencies\__init__.py", line 216, in solve
    await param._solve(**params)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\params.py", line 163, in _solve
    return await task
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot_plugin_alconna\matcher.py", line 142, in _key_getter
    await matcher.reject(prompt)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 514, in reject
    await cls.send(prompt, **kwargs)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\matcher\matcher.py", line 466, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 140, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\mute2\AppData\Local\pypoetry\Cache\virtualenvs\sorabot-hOzgpBQQ-py3.10\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1000, data={'message': 'Error: 不是本群成员'}, echo='3')
08-05 19:09:10 [SUCCESS] nonebot | OneBot V11 2871703871 | [notice.group_decrease.leave]: {'time': 1691233751, 'self_id': 2871703871, 'post_type': 'notice', 'notice_type': 'group_decrease', 'sub_type': 'leave', 'user_id': 2740324073, 'group_id': 413820772, 'operator_id': 2740324073}
```

### 额外补充
<img width="624" alt="529bb9b7822e1b60e5f1616c824aae96" src="https://github.com/A-kirami/matcha/assets/110453675/3ac27586-49fe-4878-9883-f85920c8b126">

该插件在私信、tg中都可以正常响应，应该没问题（？
[My plugin.zip](https://github.com/A-kirami/matcha/files/12266920/My.plugin.zip)

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
需要将bot也加入群聊
