### ISSUE TITLE
BUG: 反向websocket连接nb后发送本地图片闪退

### ISSUE THREAD

**Issue by hanasa2023** [A-kirami/matcha#218]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

96ccbdd

### 问题描述

反向websocket连接nb后发送本地图片闪退，若改为发送网络图片则不会出现上述情况

### 复现步骤

1.首先，创建一个发送本地图片的nb插件
2.然后加载插件，向bot发送指令。
3.最后，matcha闪退，并且websocket似乎并未正常断开连接

### 预期行为

正常发送图片

### 日志信息

```shell
12-21 17:56:32 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_ba_w
alkthrough, lineno=24)
12-21 17:56:32 [DEBUG] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_ba_walkthrough, line
no=24)
12-21 17:56:32 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_arparma_check)
, use_cache=False),))
12-21 17:56:32 [DEBUG] nonebot_plugin_ba_tools | url: https://arona.hanasaki.tech/api/chapter-map/2-1
12-21 17:56:33 [DEBUG] nonebot | Running PreProcessors...
12-21 17:56:35 [DEBUG] nonebot_plugin_ba_tools | 从/home/hanasaki/.cache/nonebot2/nonebot_plugin_ba_tools/asserts/images
/chapter_map/c250dd3b9dbefaa1f92d7af31659580a0cf603b70e301d027e3d1e3036ae6657.png加载图片……
12-21 17:56:35 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
12-21 17:57:03 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_ba_walkthrough, lineno=24) ru
nning complete
12-21 17:57:03 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_ba_tools.get_ba_walkthrough, line
no=24) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/__init__.py", l
ine 337, in run
    get_driver().run(*args, **kwargs)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi
.py", line 188, in run
    uvicorn.run(
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 
579, in run
    server.run()
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/uvicorn/server.py", lin
e 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/utils.py", line
 254, in run_coro_with_shield
    return await coro
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/message.py", li
ne 506, in check_and_run_matcher
    await _run_matcher(
> File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/message.py", li
ne 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/internal/matche
r/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/internal/matche
r/matcher.py", line 837, in simple_run
    await handler(
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/dependencies/__
init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/nonebot_plugin_ba_tools/get_ba_walkthrough/__init__.py", l
ine 39, in _
    await get_walkthrough.send(msg)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot_plugin_alconna/
matcher.py", line 706, in send
    return await _message.send(target=event, bot=bot, fallback=fallback, no_wrapper=True, **kwargs)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot_plugin_alconna/
uniseg/message.py", line 1417, in send
    res = await fn.send_to(target, bot, msg, **kwargs)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot_plugin_alconna/
uniseg/adapters/onebot11/exporter.py", line 154, in send_to
    return await bot.send(target, message, **kwargs)  # type: ignore
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/adapters/onebot
/v11/bot.py", line 237, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/adapters/onebot
/v11/bot.py", line 190, in send
    return await bot.send_msg(**params)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/internal/adapte
r/bot.py", line 176, in call_api
    raise exception
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/internal/adapte
r/bot.py", line 128, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/hanasaki/PythonProjects/nonebot-plugin-ba-tools/.venv/lib/python3.12/site-packages/nonebot/adapters/onebot
/v11/adapter.py", line 177, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_msg timeout')
12-21 17:57:04 [DEBUG] nonebot | Checking for matchers completed
12-21 17:57:06 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 3047884642 closed by peer
12-21 17:57:06 [INFO] websockets | connection closed  
```

### 额外补充

在issue[#128]中似乎有类似的问题，但当时的版本为0.2.4-0.2.5，现版本为0.4.6

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
无法复现此问题，请提供 nb 的最小可复现代码

**Comment by hanasa2023** [comment]
最小化可复现代码：[matcha#218](https://github.com/hanasa2023/matcha-218)
nb运行环境：
- 系统：
![image](https://github.com/user-attachments/assets/d4d9d47c-a50d-4a11-9454-f55407a921f7)
- python版本: 3.12.3
matcha运行环境：
- 系统：
![image](https://github.com/user-attachments/assets/ac90277b-297b-4003-91e8-e4bcbcc689c6)

**Comment by A-kirami** [comment]
请尝试更换文件类型，目前 svg 格式文件不受支持

**Comment by hanasa2023** [comment]
> 请尝试更换文件类型，目前 svg 格式文件不受支持
并非此问题，如果换为png、jpeg格式的图片仍然会出现此bug

**Comment by A-kirami** [comment]
> > 请尝试更换文件类型，目前 svg 格式文件不受支持
> > 并非此问题，如果更换为png、jpeg格式的图片仍然会出现此bug

使用你提供的最小复现更换文件类型后，matcha正确获取了图像
![image](https://github.com/user-attachments/assets/ac5b7829-3c4e-4a23-b336-49ef00075e61)
不过使用svg也没有闪退，只是无法加载图片

请到 `username\AppData\Local\com.akirami.matcha\logs` 中查看日志，并提供闪退之前的信息

**Comment by hanasa2023** [comment]
```shell
[2024-12-28][23:36:23][INFO][webview:Proxy.connect@http://tauri.localhost/assets/state-Qqg9BRYa.js:5:1469] 已连接到反向 WebSocket 服务器 ws://127.0.0.1:8080/onebot/v11/ws
[2024-12-28][23:36:24][INFO][webview:Proxy.actionHandle@http://tauri.localhost/assets/state-Qqg9BRYa.js:5:5334] [OneBot V11 标准] 收到 3047884642 的请求 send_msg: {"user_id":2969709268,"message_type":"private","message":[{"type":"image","data":{"file":"file:///home/hanasaki/PythonProjects/matcha-218/matcha_218/plugins/test/1.jpeg","type":null,"cache":"true","proxy":"true","timeout":null}}]}
```
日志中并无报错，但是实际表现为：

https://github.com/user-attachments/assets/470b2ea5-abf4-442a-af13-496c34246c62

**Comment by hanasa2023** [comment]
这可能很难做到，因为wsl运行在真机上，并且使用的还是校园网（无公网ip）。问题估计就发生在onebot协议上，在onebot协议中，图片资源的下载取决于客户端，而服务端发送给客户端的文件路径在客户端本地不存在，所以无法正确发送（显示)图片。虽然对于这种行为直接崩溃稍微有一点难绷

**Comment by hanasa2023** [comment]
> 方便的话，在群聊私聊一下提供nb的远程地址，我这边连接看看

这可能很难做到，因为wsl运行在真机上，并且使用的还是校园网（无公网ip）。问题估计就发生在onebot协议上，在onebot协议中，图片资源的下载取决于客户端，而服务端发送给客户端的文件路径在客户端本地并不存在，所以无法正确发送（显示)图片。~~虽然对于这种行为直接崩溃还是稍微有一点难绷~~事实上，现在的wsl2已经可以运行gui程序了，在wsl中安装matcha并运行，此问题就应该能够得以解决。~~是的，这不是一个bug，这是一个特性~~

**Comment by A-kirami** [comment]
用不存在的地址尝试了一下也没有出现闪退现象
![image](https://github.com/user-attachments/assets/aeae1e33-95dc-4160-ae47-0c88fa795a24)
没在wsl中跑过bot，不清楚问题在哪，看之后有没有其他人遇到相似的问题吧
